- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
- tests/unit/test_crunch_cube.py
- Add unit tests for 'count' API method
- Add integration tests for 'count' method (using fixtures)
- Implement count functionality
> Implement total cube count functionality

- src/cr/cube/crunch_cube.py
- src/cr/cube/dimension.py
- src/cr/cube/subtotal.py
- tests/integration/test_dimension.py
- tests/unit/test_dimension.py
- tests/unit/test_subtotal.py
- Add new class for subtotals ('Subtotal')
- Add unit tests for new class
- Implement all analysis of the transforms in that class
- Guard agains bad input data
> Refactor transformations

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/fruit-x-pets-array.json
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/n/projects/931610/stories/154194080)
> Operand shapes 154194080

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/cat-arr-with-single-cat.json
- tests/integration/fixtures/cubes/econ-identity-x-period.json
- tests/integration/fixtures/cubes/mr-x-single-wave.json
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/n/projects/931610/stories/154195802)
> Axis out of bounds 154195802

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/array-by-mr.json
- tests/integration/fixtures/cubes/pets-array-x-pets.json
- tests/integration/fixtures/cubes/pets-x-pets-array.json
- tests/integration/fixtures/cubes/selected-3way-2-filledmissing.json
- tests/integration/fixtures/cubes/selected-3way-filledmissing.json
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/n/projects/931610/stories/154209483)
> None type for ca x mr 154209483

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/n/projects/931610/stories/154338431)
> Fix MRxCAT percentages to add up to 100, #154338431

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/binned.json
- tests/integration/fixtures/cubes/cat-x-cat-with-empty-cols.json
- tests/integration/test_crunch_cube.py
- tests/unit/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/story/show/154336430)
> Pruning 154336430

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/single-col-margin-not-iterable.json
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/story/show/154381962)
> Zip argument 154381962

- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/story/show/154248138)
> Index not defined for col direction 154248138

- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/n/projects/931610/stories/154599334)
> Refactor pvals to include H&S, and support with tests

- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/story/show/154618272)
Needs to be rebased #19 (only last commit is relevant)
> Pruning for single cat 154618272

- src/cr/cube/dimension.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/ca-with-nets.json
- tests/integration/test_dimension.py
Per [ticket](https://www.pivotaltracker.com/story/show/154871576)
> Fix bad anchors in H&S

- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
- tests/integration/test_headers_and_subtotals.py
update tests with links to matching whaam/R ones
> use residuals and get rid of old zscore stuff;

- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
- tests/unit/test_crunch_cube.py
Per [ticket](https://www.pivotaltracker.com/story/show/155818339)
> Univariate CA 155818339

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/pets-x-fruit-hs.json
- tests/integration/test_headers_and_subtotals.py
Per [ticket](https://www.pivotaltracker.com/story/show/155641308)
> Hs for mr 155641308

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/pets-x-fruit-hs.json
- tests/integration/test_crunch_cube.py
- tests/integration/test_headers_and_subtotals.py
Per [ticket](https://www.pivotaltracker.com/story/show/156264181)
- Fix margin calculation
- Also fix CA calculations
Needs to be rebased on #35 (only last commit relevant)
> Fix cell props for MR cubes

- .gitignore
- src/cr/cube/crunch_cube.py
https://www.pivotaltracker.com/story/show/154613258
> correct univariate_ca method

- src/cr/cube/crunch_cube.py
- tests/integration/test_crunch_cube.py
https://www.pivotaltracker.com/story/show/155080499
> Export messed up for cubes with HS and Pruning

- src/cr/cube/dimension.py
- tests/unit/test_dimension.py
https://www.pivotaltracker.com/story/show/157293490
> fix formatting hs in 3d cubes

- src/cr/cube/dimension.py
- tests/unit/test_dimension.py
https://www.pivotaltracker.com/story/show/157444596
> fix ordering of stacked insertions

- src/cr/cube/crunch_cube.py
- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/cat-x-items-x-cats-hs.json
- tests/integration/test_headers_and_subtotals.py
https://www.pivotaltracker.com/story/show/157556884
> fix margin calculations when transformations are applied

- src/cr/cube/crunch_cube.py
- src/cr/cube/cube_slice.py
- src/cr/cube/measures/data_table.py
- src/cr/cube/measures/index.py
- src/cr/cube/measures/scale_means.py
- src/cr/cube/utils/__init__.py
- tests/integration/test_cube_slice.py
- tests/unit/test_crunch_cube.py
- tests/unit/test_cube_slice.py
Per [ticket](https://www.pivotaltracker.com/story/show/157772177)
- Write unit tests for CubeSlice (always do only TDD)
- Write the CubeSlice class
> [#157772177]: Initial commit for CubeSlice

- src/cr/cube/crunch_cube.py
https://www.pivotaltracker.com/story/show/158287278
> row and col dim index props

- src/cr/cube/crunch_cube.py
- src/cr/cube/cube_slice.py
- src/cr/cube/subtotal.py
- tests/unit/test_crunch_cube.py
- tests/unit/test_cube_slice.py
- tests/unit/test_dimension.py
- tests/unit/test_subtotal.py
> Support ca as 0th cube #158497249

- tests/integration/fixtures/__init__.py
- tests/integration/fixtures/cubes/cat-x-cat-pruning-hs.json
- tests/integration/test_cube_slice.py
Additional tests to ensure H&S with pruning doesn't break on slices.
> Add tests with pruning and H&S on both dimensions

- HISTORY.md
- README.md
- setup.py
- src/cr/cube/measures/scale_means.py
- tests/unit/test_scale_means.py
- Use TDD and parametrized tests to cover edge cases (mostly
single-element CAT variables)
- Refactor methods to allow tests to pass
- Keep all the other tests in cr.cube and cr.exporter passing
> Refactor and fix scale means for edge cases

- .pre-commit-config.yaml
- setup.py
- src/cr/cube/crunch_cube.py
- src/cr/cube/cube_slice.py
- src/cr/cube/util.py
- tests/unit/test_crunch_cube.py
- Display name, type, and slices
- Default slices contents to counts
> Add __repr__ to CubeSlice and CrunchCube

- MANIFEST.in
- Makefile
- src/cr/__init__.py
- src/cr/cube/crunch_cube.py
- src/cr/cube/cube_slice.py
- src/cr/cube/enum.py
- src/cr/cube/util.py
- tests/integration/test_crunch_cube.py
- tests/integration/test_cube_slice.py
- tests/integration/test_index.py
- tests/unit/test_crunch_cube.py
- tests/unit/test_cube_slice.py
- tests/unit/test_enum.py
- tests/unit/test_util.py
- tests/unitutil.py
- tox.ini
Bring test coverage to 100%.
Let's get this CR'ed and merged to master. No need for a new release but we should base all future branches on this.
> Full test coverage

- src/cr/cube/cube_slice.py
- tests/fixtures/mr-x-cat-both-single-element.json
- tests/integration/test_cube_slice.py
Per [this](https://www.pivotaltracker.com/story/show/162415980) 🎫
> Single element index table

- HISTORY.md
- README.md
- src/cr/cube/__init__.py
- Bump version
- Update readme
- Update history
> Bump version

- src/cr/cube/cube_slice.py
- tests/unit/test_cube_slice.py
* Add unit test for new property
* Add 'can_compare_pairwise' property
> Check if slice can compare pairwise

- src/cr/cube/measures/scale_means.py
- tests/fixtures/scale_means/cat-single-element-x-cat.json
- tests/integration/test_scale_means.py
- tests/unit/test_scale_means.py
* Support with integration test from production
* Don't drop the 0th dimension even if it's just a single element
* Replicates behavior of how crunch cube drops dimensions
* Fix unit tests
> Fix reshaping valid indices in scale means

- src/cr/cube/dimension.py
- src/cr/cube/slices.py
- tests/fixtures/cat-with-means-and-insertions.json
- tests/fixtures/cat-x-mr-with-means.json
- tests/fixtures/deck-with-mean.json
- tests/fixtures/means-3d.json
- tests/fixtures/mr-mean-filt-wgtd.json
- tests/integration/test_frozen_multiple_response.py
- tests/integration/test_slices.py
For starters - increase coverage...
> Continue development of Frozen Cube

- src/cr/cube/cubepart.py
- src/cr/cube/stripe.py
- tests/fixtures/scale_means/bolshevik-hair.json
- tests/integration/test_scale_means.py
Scale means for strand must be equal when we apply hiding transforms
> Bug fix for scale means after hiding [#172489121]

- src/cr/cube/cubepart.py
- tests/integration/test_scale_additional_measures.py
- tests/integration/test_scale_means.py
- median cols and rows for scales
- std dev and std err for scales
> Additional summaries for scales

- src/cr/cube/cubepart.py
- tests/integration/test_cube.py
- tests/integration/test_cubepart.py
- tests/integration/test_multiple_response.py
- Add standard_error and standard_deviation measures in cubepart.strand
> Stdandard deviation and standard error for strand [#173418834]

- src/cr/cube/cubepart.py
- tests/integration/test_cube.py
- Implement "margin of error" for 1D cubes
- Fix coverage
> MoE for 1D cubes

- src/cr/cube/cube.py
- tests/integration/test_cube.py
- tests/unit/test_cube.py
Fix valid_idxs to handle transposition in case of num array, expose valid count measure for missing calc
> Fix valid_idxs to handle transposition in case of num array, expose valid count measure for missing calc

- src/cr/cube/cubepart.py
- src/cr/cube/matrix/assembler.py
- src/cr/cube/matrix/cubemeasure.py
- src/cr/cube/matrix/measure.py
- src/cr/cube/measures/pairwise_significance.py
- src/cr/cube/noa/smoothing.py
- tests/integration/test_cubepart.py
- tests/integration/test_matrix.py
- tests/integration/test_pairwise_significance.py
- tests/integration/test_scale_additional_measures.py
- tests/integration/test_scale_means.py
- tests/unit/matrix/test_assembler.py
- tests/unit/matrix/test_cubemeasure.py
- tests/unit/matrix/test_measure.py
- tests/unit/test_cubepart.py
- tests/unit/test_smoothing.py
Jan-20-2021 STATUS: Code complete, ready for merging to master. Note there is a companion branch/PR on zoom that is required in order to pin to this new version.
> Measure consolidation 176212559

- src/cr/cube/cube.py
- src/cr/cube/matrix/assembler.py
- src/cr/cube/matrix/cubemeasure.py
- src/cr/cube/stripe.py
- tests/fixtures/numeric_arrays/num-arr-means-x-mr.json
- tests/integration/test_numeric_array.py
- tests/unit/matrix/test_assembler.py
- `columns_base` props for NumericArray matrix types
- `table_base` for numeric array stripe
For reference please see the activities section in here: https://www.pivotaltracker.com/story/show/176085256
> Columns base properties for numeric array matrices

- src/cr/cube/cube.py
- src/cr/cube/dimension.py
- src/cr/cube/matrix/cubemeasure.py
- tests/fixtures/numeric_arrays/num-arr-means-grouped-by-date.json
- tests/integration/test_cubepart.py
- tests/integration/test_matrix.py
- tests/integration/test_numeric_array.py
- tests/unit/test_cube.py
Working PR, will delete after merge with @ernestoarbitrio 's work
> Num arr order cube 176728242

- src/cr/cube/cubepart.py
- tests/integration/test_headers_and_subtotals.py
This ended up being way easier when I realized that we were just re-calculating the proportions
> Variance derived measures should be missing when proportion is missing

- src/cr/cube/matrix/assembler.py
- src/cr/cube/matrix/measure.py
- tests/integration/test_headers_and_subtotals.py
- tests/unit/matrix/test_assembler.py
- tests/unit/matrix/test_measure.py
Omit subtotal diffs for sum and share of sum
> Omit subdiff share sum 177500997

- src/cr/cube/matrix/assembler.py
- tests/integration/test_headers_and_subtotals.py
- tests/unit/matrix/test_assembler.py
Row/Column margins of subdiffs should remain, but their 1D bases are nan.
> Subdiff base again 177369190

- src/cr/cube/cubepart.py
- src/cr/cube/enums.py
- src/cr/cube/matrix/assembler.py
- src/cr/cube/matrix/measure.py
- tests/integration/test_cubepart.py
- tests/integration/test_headers_and_subtotals.py
- tests/integration/test_numeric_array.py
- tests/unit/matrix/test_measure.py
`Slice objects`
Rename:
- share_sum -> column_share_sum
Add:
- row_share_sum
- total_share_sum
> Additional share sum measures 177548812

- src/cr/cube/matrix/measure.py
- tests/fixtures/overlaps/cat-x-mr-gender-x-all-pets-owned.json
- tests/integration/test_pairwise_significance.py
* rfctr architecture wrt/ row_id
* add test case from alpha
> fix: overlaps

- src/cr/cube/cube.py
- tests/unit/test_cube.py
* Drive by TDD, create a unit test that expects correct behavior for the
population fraction, based on the `is_cat_date` filter stats setting
* Implement correct functionality
> [#177923295]: Pop fraction for CAT DATE

- src/cr/cube/cubepart.py
- tests/integration/test_cubepart.py
* Add test cases for cat array and pop counts
* Fix pop counts to not be divided between subvariables
> [#178045298]: Fix pop counts

- src/cr/cube/stripe/measure.py
- tests/fixtures/scale_means/univariate-ca-subvar.json
- tests/integration/test_scale_means.py
fixes : https://sentry.io/organizations/crunchio/issues/2276461200/?project=155823&referrer=slack
> [#178155151]: fix scale measures when total counts is zero

- src/cr/cube/cubepart.py
- src/cr/cube/dimension.py
- src/cr/cube/enums.py
- src/cr/cube/matrix/assembler.py
- src/cr/cube/matrix/measure.py
- tests/fixtures/cat-4-x-cat-5.json
- tests/integration/test_cubepart.py
- tests/integration/test_headers_and_subtotals.py
- tests/integration/test_matrix.py
- tests/integration/test_scale_additional_measures.py
- tests/integration/test_scale_means.py
- tests/unit/matrix/test_assembler.py
- tests/unit/matrix/test_measure.py
- tests/unit/stripe/test_insertion.py
- tests/unit/test_cubepart.py
- tests/unit/test_dimension.py
I think scale medians are looking good. Also have scale mean and scale mean standard deviation. I'm thinking it makes sense to merge these in together as an intermediate point. I can't yet do scale mean standard error because it depends on the margin, so this is all of the easy scale count measures.
What's needed so that we can sort by these marginal measures by value? Do we need a `_SortRowsByMarginHelper`?
> Measure consolidation

- src/cr/cube/dimension.py
- tests/integration/test_cubepart.py
- tests/unit/test_dimension.py
* Drive by TDD
* Implement functionality by adding hidden element IDs for MR insertions
> [#178579890]: Hide MR insertions

- src/cr/cube/cubepart.py
- src/cr/cube/dimension.py
- src/cr/cube/matrix/assembler.py
- src/cr/cube/stripe/assembler.py
- tests/integration/test_headers_and_subtotals.py
* Drive with TDD
* implement functionality similarly to other elements idxs
> Indexes of differences

- src/cr/cube/cubepart.py
- tests/integration/test_cubepart.py
- tests/unit/test_cubepart.py
add tab_label, tab_alias, rows_dimension_description public properties in _Strand
> [179652205]: Add public properties in `_Strand` worthed for half-tidy profile exports

- src/cr/cube/dimension.py
- src/cr/cube/matrix/assembler.py
- src/cr/cube/stripe/assembler.py
- tests/unit/matrix/test_assembler.py
- tests/unit/stripe/test_assembler.py
- tests/unit/test_dimension.py
* Drive by TDD
* Add `fill` prop to `_Subtotal`
* Add interleaved subtotal fills to row dimension fills in assemblers
> Subtotal fills

- src/cr/cube/dimension.py
- src/cr/cube/matrix/measure.py
- tests/unit/test_dimension.py
Match frontend authority for frontend.
> Change authority sequence 179728648

- src/cr/cube/dimension.py
- tests/integration/test_dimension.py
- tests/unit/stripe/test_insertion.py
- tests/unit/test_dimension.py
This has a lot of failing unit tests, and I haven't checked that it actually fixes the issue (but it basically undoes what I changed in the shim, so I think it should). Wanted to see what you thought before cleaning it up.
> Another attempt at fixing color when insertions are in weird order
