src/cr/cube/crunch_cube.py, tests/integration/test_crunch_cube.py
- Don't deflate margin if first dimension has a single element and if
the cube is 3D
- The extra (0th) dimension is needed for proper slicing
- Change expectation in the corresponding test
=> [#158907364]: Fix margin for 3D

src/cr/cube/crunch_cube.py, src/cr/cube/cube_slice.py, src/cr/cube/dimension.py, src/cr/cube/measures/index.py, src/cr/cube/mixins/data_table.py, src/cr/cube/utils/__init__.py, tests/unit/test_cube_slice.py
- Use lazyproperty in CubeSlice
- Make ndim and shape properties explicit, to allow for better fixture
creation, when doing exporter tests
=> Make some CubeSlice properties explicit

README.md, setup.py, src/cr/cube/cube_slice.py, tests/unit/test_cube_slice.py
- Deprecation warning when `shape` property is used
- Implement `get_shape` method, that uses `prune` argument
- Unit tests
=> Deprecate CubeSlice shape property

Makefile, README.md, setup.cfg, setup.py, src/cr/cube/crunch_cube.py, src/cr/cube/dimension.py, src/cr/cube/measures/scale_means.py, tests/integration/fixtures/__init__.py, tests/integration/fixtures/cubes/ca-subvar-hs-x-mr-x-ca-cat.json, tests/integration/test_crunch_cube.py, tests/integration/test_dimension.py, tests/integration/test_headers_and_subtotals.py, tests/unit/test_crunch_cube.py, tests/unit/test_dimension.py, tests/unit/test_scale_means.py, tests/unit/unitutil.py, tests/unitutil.py
This is a fairly thorough refactor of cr.cube.dimension.
Let's discuss when we speak next.
=> Refactor dimension

src/cr/cube/cube_slice.py, tests/unit/test_cube_slice.py
* For a slice that's a Categorical Array, if it's to be treated as the
0th cube in a Tabbook, we need to check if it actually has scale means
on it's column dimension (and not the 0th categorical one, because there
aren't any)
* Change the unit tests accordingly
=> Fix scale means for CA as 0th

src/cr/cube/cube_slice.py, tests/unit/test_cube_slice.py
* This is essentially just a categorical dimension (even though it's
paired with a respective CA_SUBVAR dimnension). If the subvar dimension
is only used for slicing (of a 3D cube), we can then treat individual
slices as categorical x categorical.
=> Allow pairwise for `CA_CAT` dimension type

src/cr/cube/distributions/wishart.py, tests/fixtures/pairwise-with-zero-margin.json, tests/integration/test_pairwise.py
Per [ticket](https://www.pivotaltracker.com/story/show/163663195)
* Add integration test with a cube that has zeros in the rows margin
(column), which cause the pairwise calculation to fail
=> Reproduce bug with pairwise calculation

README.md, src/cr/cube/__init__.py, src/cr/cube/crunch_cube.py, src/cr/cube/cube_slice.py, tests/fixtures/ca-as-0th.json, tests/integration/test_crunch_cube.py
* Provide integration test that demonstrates existing bug
* Fix the functionality by moving the key calculation to CubeSlice
instead of CrunchCube, allowing each slice to control whether it is to
be treated as a 0th element in tabbook array of cubes (slices)
=> Fix population counts for Categorical Array, as 0th cube in tabbooks

src/cr/cube/cube_slice.py, src/cr/cube/enum.py, tests/unit/test_cube_slice.py
* TDD - start from unit tests
* Extract ALLOWED_PAIRWISE_TYPES to enum.py
* Implement logic
=> Allow additional types when comparing pairwise

src/cr/cube/crunch_cube.py, src/cr/cube/dimension.py, src/cr/cube/util.py, tests/unit/test_dimension.py
* Make `all_elements` and `valid_elements` parts of the interface
* Use newly available properties from `CrunchCube`
* Fix unit tests
=> Eliminate `memoize` from dimension.py

src/cr/cube/crunch_cube.py, src/cr/cube/dimension.py, tests/unit/test_dimension.py
Break ugly method that does 2 things that shouldn't be together into two independent methods.
=> Decouple pruning and missingness

src/cr/cube/cube_slice.py, src/cr/cube/measures/pairwise_significance.py
* Account for row dimension H&S when creating indices for each column
* Account for col dimension H&S when returning result (intersperse NaNs)
=> Fix how H&S is treated for pairwise indices

src/cr/cube/dimension.py
* Element ids sometimes come through shim as str (or unicode)
* When getting the element transform from the dict, make sure to check
for both integer and string versions of the key
* This needs to be properly fixed in the shim code
=> Fix transforms element ids as str

src/cr/cube/slices.py, tests/integration/test_slices.py, tests/unit/test_slices.py
* Allow insertion vectors to have NaNs for column indexes
* Allow assembled vectors to insert NaNs between normal column index
values, for the opposite dimension insertion vectors
=> Column index works with insertions

src/cr/cube/matrix.py, src/cr/cube/slices.py, src/cr/cube/vector.py, tests/unit/test_slices.py
Normalizing method order and documenting along the way of learning this new module.
=> rfctr: normalize and document

src/cr/cube/cubepart.py, src/cr/cube/stripe.py
_StripeInsertionRow has no .fill property, which causes a failure on export of a chart that includes subtotals. There is no test that exercises this case in exporter. Add a test that reproduces this error
in exporter integration tests and add _StripeInsertionRow.fill.
=> fix: add .fill property to _StripeInsertionRow

src/cr/cube/cube.py, src/cr/cube/cubepart.py, src/cr/cube/matrix.py
Add `cr.cube.cube.CubeSet` which takes a full tabbook response set (multiple cube-responses) and provides table-wise partition sets and other appropriate properties characterizing the overall response-set.
=> Add cr.cube.cube.CubeSet

src/cr/cube/cubepart.py, tests/fixtures/econ-nodata-no-dims.json, tests/fixtures/om-sgp8334215-vn-2019-sep-19-strand.json, tests/fixtures/om-sgp8334215-vn-2019-sep-19.json, tests/integration/test_cubepart.py, tests/unit/test_cubepart.py
- New methods `has_valid_data` for `_Strand`, `_Slice` and `_Nub` for checking the data validity for cube partitions
- New tests (unit + integration) covering the new properties
=> New property in cubepart for data validity

src/cr/cube/cubepart.py, src/cr/cube/matrix.py
Some refactorings to trim-down and clarify transform-application matrix objects.
=> Matrix refactoring

src/cr/cube/cubepart.py, src/cr/cube/dimension.py, src/cr/cube/matrix.py, src/cr/cube/stripe.py, tests/fixtures/cat-subtot-order.json, tests/fixtures/cat-x-cat-4x4.json, tests/fixtures/transforms/generic-transforms-dicts.json, tests/integration/test_cube.py, tests/integration/test_cubepart.py, tests/integration/test_dimension.py, tests/unit/test_cubepart.py, tests/unit/test_dimension.py, tests/unit/test_matrix.py, tests/unit/test_stripe.py
Fix problem where pre-ordering anchor-idx was used for locating inserted subtotal vectors, leading to incorrect placement in many cases when an explicit vector ordering transform was applied to a dimension having inserted vectors.
=> Fix anchor idx bug 172616313

src/cr/cube/cube.py, tests/fixtures/cat-x-cat.json, tests/fixtures/univariate-categorical.json, tests/unit/test_cube.py
Change payload location of `"title":` field to `result.title`.
=> fix: cube title payload location discrepancy

src/cr/cube/cubepart.py, src/cr/cube/measures/pairwise_significance.py, tests/unit/test_cubepart.py
The array of scale-mean pairwise-indices collapses when all the tuples it contains are empty, producing a wrong shape. Change interface to return a tuple of tuples and avoid numpy idiosyncrasies on edge cases.
=> fix: collapsed scale-mean-pairwise-indices

src/cr/cube/dimension.py, tests/integration/test_cubepart.py
Add sensitivity to `"hide": true` element within an insertion transform such that insertions "copied" into the transforms from a variable can be suppressed without having to delete it (and then later work out a way to recover it if wanted again).
=> xfrm: insertions can be hidden

src/cr/cube/collator.py, src/cr/cube/cubepart.py, src/cr/cube/enums.py, src/cr/cube/matrix/assembler.py, src/cr/cube/matrix/cubemeasure.py, src/cr/cube/matrix/measure.py, tests/fixtures/cat-4-x-cat-5.json, tests/integration/test_collator.py, tests/integration/test_cubepart.py, tests/integration/test_matrix.py, tests/unit/matrix/test_assembler.py, tests/unit/matrix/test_cubemeasure.py, tests/unit/matrix/test_measure.py, tests/unit/test_collator.py
Install sort-by-value machinery and wire it up for column-percent.
This is so-far limited to sort-rows-by-column-percent-column, just because there's no call yet for sorting columns by column-percent. That can be added with minimal additional work when and if the need arises.
Note this does not include sort-rows-by-the-All-percent-marginal that typically appears at the right side of such a crosstab. That will require some additional noodling on how we handle marginals (and particularly marginal-ranges) in the new measure architecture.
=> Sort by column percent 176603042

src/cr/cube/cube.py, tests/fixtures/numeric_arrays/num-arr-means-x-mr.json, tests/integration/test_numeric_array.py, tox.ini
Related to this sentry error: https://sentry.io/organizations/crunchio/issues/2215234980/?referrer=slack
RATIONALE:
In case of NUM ARRAY X MR we have 3 dimensions NUM_ARR, MR_SUBVAR, MR_CAT
The old implementation had a bug cause we flip the entire shape of the dimension: shape[::-1] but in case of MR the SUBVARS and the SELECTED dims cannot be swapped.
=> Bug fix for shape calculation in case of NUM_ARR X MR (or CA)

src/cr/cube/matrix/assembler.py, src/cr/cube/matrix/measure.py, src/cr/cube/matrix/subtotals.py, src/cr/cube/stripe/insertion.py, src/cr/cube/stripe/measure.py, tests/integration/test_headers_and_subtotals.py, tests/unit/matrix/test_assembler.py, tests/unit/matrix/test_measure.py, tests/unit/matrix/test_subtotals.py, tests/unit/stripe/test_insertion.py, tests/unit/stripe/test_measure.py
Bases are not considered valid for subtotal differences along the same dimension. This allowed simplifying the design of subtotal differences because the case where SumSubtotal != SumDiffSubtotal is no longer valid so we can unify them.
=> Subdiff 177369190

src/cr/cube/dimension.py, tests/integration/test_dimension.py, tests/integration/test_matrix.py, tests/integration/test_multiple_response.py, tests/integration/test_numeric_array.py, tests/unit/test_dimension.py
For array dimensions e.g. `DT.NUM_ARRAY`, `DT.MR`, `DT.CA`, handle hiding transform using explicit subvarible id VS positional idx in the element dicts.
**_Keeps the retro-compatibility with the older expressions_**
=> enable hiding using explicit subvar id in case of array vars

src/cr/cube/enums.py, src/cr/cube/stripe/assembler.py, tests/integration/test_stripe.py, tests/unit/stripe/test_assembler.py
Wire up _Strand sort-by-value for "univariate-measure" keyword case.
This should fix the existing alpha-Sentry error on sort-by-value for FREQUENCY analyses (aka. 1D card, _Strand).
I'll continue work on another branch to add detailed unit tests for these and add the remaining measures and so forth.
=> spike: plug FREQUENCY sort-by-value gap

src/cr/cube/stripe/assembler.py, tests/integration/test_stripe.py
Measure keyword is distinct for univariate measure, "percent" instead of "col_percent" as we use for the measure itself in exporter.
This makes sense because there is only one kind of percent measure for a frequency (always univariate) analysis and that is not column-percent. Rather it is what we might call "total_percent" but there's no need for a modifier word in this case since there's just the one.
=> fix: sort-by-value keyword to "percent"

src/cr/cube/cubepart.py, src/cr/cube/matrix/assembler.py, src/cr/cube/matrix/measure.py, tests/integration/test_headers_and_subtotals.py, tests/unit/matrix/test_assembler.py, tests/unit/matrix/test_measure.py
Can't calculate the scale median on the row of a row subtotal difference or the column of a column subtotal difference.
=> Don't show scale median on row/column of subotal difference

src/cr/cube/cube.py, src/cr/cube/cubepart.py, src/cr/cube/matrix/assembler.py, src/cr/cube/matrix/cubemeasure.py, src/cr/cube/matrix/measure.py, src/cr/cube/stripe/assembler.py, src/cr/cube/stripe/cubemeasure.py, src/cr/cube/stripe/measure.py, tests/integration/test_cubepart.py, tests/integration/test_numeric_array.py, tests/unit/matrix/test_assembler.py, tests/unit/matrix/test_measure.py
`valid_counts` (weighted or unweighted) basically are equal to `counts` and `unweighted_counts` when the payload has these measures inside. This because it's up to cube to get the proper counts in it's measures.
This PR removes all the valid counts logic
=> [#177917018]: move the whole logic of valid counts in the actual weighted and unweighted counts

src/cr/cube/cubepart.py, src/cr/cube/matrix/assembler.py, tests/integration/test_headers_and_subtotals.py, tests/unit/matrix/test_assembler.py
exporter used the `*_margin` both as the "Weighted N" in the summary row and as the numerator for calculating the proportions in the "All" column.
In the first case, we want to set to nan for subtotal difference columns because all other measures are set to nan.
But in the second case, we want to keep the number.
Fix by calculating the `*_margin_proportion` in cr.cube and using that in exporter. I can also changing by having two kinds of "`margin`s", but I thought it'd be hard to understand their difference (especially since the difference between base and margin is already a little fuzzy)
=> Set weighted N to - for subdifference columns

src/cr/cube/matrix/assembler.py, src/cr/cube/matrix/measure.py, tests/integration/test_pairwise_significance.py
fix https://sentry.io/organizations/crunchio/issues/2377940211/?referrer=slack
The map operation for shifting the indices (for means) according to the column order doesn't work with the hiding transforms, this required the computation of the pairwise indices directly in the assembler and get rid of the measure class
=> [#178242141]: Bug fix hypothesis testing means with hiding transforms

src/cr/cube/cube.py, tests/unit/test_cube.py
* For NUMA, when we have shape mismatch for counts, we mustn't crash
* Drive by TDD, add unit test
* Add a guard in `_BaseMeasure` to prevent the crash
=> [#178545213]: Fix weighted counts

src/cr/cube/cubepart.py, src/cr/cube/stripe/assembler.py, src/cr/cube/stripe/measure.py, tests/unit/stripe/test_assembler.py, tests/unit/stripe/test_measure.py, tests/unit/test_cubepart.py
- Consolidate population measure so that it can be sorted by
- Add fallback to payload order for 1D sort-by-value
=> [178611312]: sort-by-value stripe population consol

src/cr/cube/stripe/cubemeasure.py, src/cr/cube/stripe/measure.py, tests/unit/stripe/test_cubemeasure.py, tests/unit/stripe/test_measure.py
This consolidates weighted & unweighted counts in stripe (to match how they are in matrix) and as a consequence avoids adding over num array subvariables for the weighted base (a previous pass had fixed this for unweighted bases only).
=> [178371707]: consolidate stripe counts and fix num-array base for weighted

src/cr/cube/matrix/measure.py, tests/integration/test_headers_and_subtotals.py, tests/unit/matrix/test_measure.py
Use `nansum` vs `sum` for denominator
=> [178710104]: bug fix for row share of sum and total share of sum

src/cr/cube/collator.py, src/cr/cube/dimension.py, src/cr/cube/enums.py, src/cr/cube/matrix/assembler.py, src/cr/cube/stripe/assembler.py, tests/integration/test_cubepart.py, tests/unit/matrix/test_assembler.py, tests/unit/stripe/test_assembler.py, tests/unit/test_collator.py, tests/unit/test_dimension.py
Implements sort-by-label in cube. 
I think it's pretty much ready, but I have one question in comments about how to make something more idiomatic - we special case `nan`s when sorting, but `np.isnan` gives error on string types (before all of the sortable things were numeric, but we're now adding a string type in label).
=> Allows sorting by label

src/cr/cube/dimension.py, tests/fixtures/cat-x-mr-unicode-sv-alias.json, tests/integration/test_dimension.py
The tests may be overkill because we won't have to support python 2 for much longer, but I think this fix is worth it (I think the code is actually clearer than the original).
=> Fix unicode bug in python 2.7 for element id shims

src/cr/cube/collator.py, src/cr/cube/dimension.py, tests/fixtures/mr_insertions/cat-x-mr.json, tests/integration/test_collator.py, tests/integration/test_cubepart.py, tests/unit/test_collator.py, tests/unit/test_dimension.py
This ended up being slightly bigger than expected because MR insertions can be anchored before or after elements (cat subtotals can only be anchored after).
The other bit of weirdness is the way that we use negative indexes to indicate categorical subtotals. Derived MR subtotals do not have negative indexes like the categorical ones, so the index has to be created from both base and derived elements.
=> Mr insertion explicit order 179379022

src/cr/cube/stripe/assembler.py, tests/unit/stripe/test_assembler.py
Performs sorting by value of share_sum in cube (A separate PR allowed this through validation)
=> [180196294]: add share of sum as a univariate sort-by-value option

.gitignore, .pre-commit-config.yaml, docs/source/conf.py, src/cr/cube/collator.py, src/cr/cube/cube.py, src/cr/cube/cubepart.py, src/cr/cube/dimension.py, src/cr/cube/matrix/assembler.py, src/cr/cube/matrix/cubemeasure.py, src/cr/cube/matrix/measure.py, src/cr/cube/matrix/subtotals.py, src/cr/cube/stripe/assembler.py, src/cr/cube/stripe/measure.py, tests/fixtures/numeric_arrays/num-arr-sums-with-nan-values.json, tests/integration/test_cubepart.py, tests/integration/test_numeric_array.py, tests/unit/matrix/test_assembler.py, tests/unit/matrix/test_measure.py, tests/unit/stripe/test_measure.py, tests/unit/test_cubepart.py
When a 1D cube sum measure contains nan values share of sum will always be all nans cause of the `np.sum` instead of `np.nansum`
=> [182919278]: fix share of sum measure

src/cr/cube/dimension.py, tests/integration/test_cubepart.py
If an MR insertion doesn't exist by name, don't error, just don't hide it. Can happen in fused scorecards.
=> [182979152]: fix bug for hiding nonexistant mr insertion

src/cr/cube/dimension.py, tests/integration/test_dimension.py
Add `repr` to various sequence classes, to ease the work in console. For example, if we're dealing with a dimension class, it'd be nice to be able to "just" see its type and elements, without having to resource to its fields/properties. This is especially useful for sequence classes that use generators and don't print out their contents by default.
=> [#183769192]: Add `repr` to various sequences

src/cr/cube/dimension.py, tests/fixtures/scorecard.json, tests/integration/test_cubepart.py, tests/unit/test_dimension.py
The shim layer of element ids gets confused by transforms on a scorecard's fused variables dimension
=> [183976784]: allow scorecard xforms

src/cr/cube/dimension.py, tests/integration/test_cubepart.py
Since we haven't been using the sort by value `fixed` elements,  we haven't noticed that they don't get shimmed the same way that other element ids do so that cr.cube understands the "bogus ids".
=> [184374302]: translate fixed elements

src/cr/cube/dimension.py, src/cr/cube/enums.py, tests/integration/test_cubepart.py, tests/unit/test_dimension.py
Makes datetimes shimmed like subvariables are so that cr.cube can understand both deck and dashboard formats of transforms for datetimes. (this way we don't have to shim in the "dashboard shim")
=> Dashboard datetime xform 184468428

src/cr/cube/dimension.py, tests/fixtures/cat-x-datetime.json, tests/integration/test_cubepart.py, tests/integration/test_dimension.py, tests/unit/test_dimension.py
Allows exporter to reflect the date format requested on the variable's view instead of using the date format from zz9 on dimensions.
=> Datetime label format 184749447

src/cr/cube/dimension.py, tests/fixtures/ca-cat-x-ca-subvar.json
Fixes bug where exporter tests are failing because it is possible for the format to be set to `null`. See https://master.ci.crint.net/blue/organizations/jenkins/Crunch-io%2Fzoom/detail/PR-6807/1/tests/
=> [184749447]: fix bug where format is set to None

src/cr/cube/dimension.py, tests/fixtures/not-mr-cats.json, tests/integration/test_cube.py, tests/unit/test_dimension.py
Last week, we found [sentry errors](https://crunchio.sentry.io/issues/4437198961/?project=155823&referrer=slack).
Looking into it, I think the problem was that a categorical dimension was being interpreted as an MR cats one, because it had the "subreferences" key (but was an empty list) and the categories were logical-looking.
I believe part of the source of this was Bob's refactoring to remove the convoluted logic about MR cats must come after a MR subvars dimension, but rather than reintroduce that, I've fixed at least this case by making sure that subreferences isn't an empty list for it to count as an MR.
=> [185959348]: avoid interpreting as mr cats if no subvars

src/cr/cube/dimension.py, tests/integration/test_dimension.py, tests/unit/test_dimension.py
https://www.pivotaltracker.com/story/show/187090869
deepcopy(s) causing OOM on task system
=> Remove deepcopy from the codebase
